### ISSUE TITLE
menu mobile display

### ISSUE THREAD

**Issue by wwgriffin** [NateWr/food-and-drink-menu#16]
On Iphone 6, menu displays on mobile well on landscape, but looks wonky on portrait

On Iphone 4, doesn't display well on landscape nor portrait

Any suggestions on how to fix?

reference: squeezejuicerybuffalo.com/menu

**Comment by NateWr** [comment]
Hi @wwgriffin. The template is designed to collapse into a vertical listing on small screens (<450px), with the image, title, price and description in a vertical line. It looks like your theme has some padding that it needs to clear on the title and description at this level, but otherwise looks ok to me.

It looks like you're using a theme from Proteus Themes. Primoz, who runs that shop, has been really good at ensuring support for my plugins. I'm sure he'll get a fix out for this soon. I'll get in touch with him, but you might also want to file a support request through their support system.

**Comment by wwgriffin** [comment]
Thanks, Nate!

**Comment by NateWr** [comment]
Hi @wwgriffin, it looks like Primoz is on holiday at the moment, so it may be a few weeks before a fix is out.

**Comment by wwgriffin** [comment]
No worries, brother.  A friend helped me with a short-term fix.  Thanks so
much for following up with me.  Be great.

**Comment by primozcigler** [comment]
Hi @NateWr and @wwgriffin!

As Nate said, I was on vacations, but the update of the theme with the fix will be available soon - probably by tomorrow.

**Comment by wwgriffin** [comment]
Thanks so much!  A friend of mine helped with a hack fix, but there still
are some padding issues on mobile.  I will get my partner to send me his
themeforest username and API so that I can update the theme on our
wordpress site.

squeezejuicerybuffalo.com/menu

Thanks again!
