### ISSUE TITLE
Common price in multi-lingual sites

### ISSUE THREAD

**Issue by JPG-Consulting** [NateWr/food-and-drink-menu#23]
Each year some restaurants update their prices and on a multilingual site I found out that changing the price in one language will only affect that language... This means that yu have to go over every single translation changing the price of that item.

Would it be possible to change the price in any translation in such a way that it reflects the price in all the other translations?

**Comment by NateWr** [comment]
Are you using WPML or Polylang? The [wpml-config.xml](https://github.com/NateWr/food-and-drink-menu/blob/master/wpml-config.xml#L10) indicates the `fdm_item_price` post meta value should be translated.

That's important to keep around because many users translate to different currencies for different languages. But if you remove that line, it might keep that post meta data.

I'm not sure how WPML/Polylang read the `wpml-config.xml` file or how the data is updated, but you might need to deactivate/reactivate the plugin after making the change.

**Comment by JPG-Consulting** [comment]
I used Polylang but I'm now starting to look at it with WPML as it seems to have some more options.
